version: '3.8'

services:
  web:
    image: yassine0223/cloudproject:latest
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppassword
    ports:
      - "3306:3306"
